routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix'=>'adminzone'], function()
    {
        Route::get('/', function()
        {
            return view('admin.dashboard');
        });
        Route::resource('products','ProductsController');    
        Route::resource('pages','PagesController');
        Route::resource('categories','CategoriesController');
        Route::post('products/create','ProductsController@save');
        Route::get('products/edit/{id}','ProductsController@edit');
        Route::post('products/{id}/edit','ProductsController@update');    
        Route::get('categories/edit/{id}','CategoriesController@edit');
        Route::post('categories/edit/{id}','CategoriesController@update');  
        Route::get('orders','OrdersController@index');
        Route::delete('orders/{id}','OrdersController@destroy')->name('deleteOrder');
        Route::get('orders/{id}','OrdersController@readOrder')->name('readOrder');


        Route::get('elfinder',function(){
            return view('admin.elfinder');
        });

        Route::get('connector','ElfinderController@connector');
        Route::post('connector','ElfinderController@connector');

    });
});



// Route::get('/', function()
// {
//     $products = App\Products::where('public', '=', 1)->get(); // получаем все, что касается товара (название, цена....)
//     $categories = App\Category::all();
//     $parameters = App\parameters::all();//получаем все параметры
//     $images = explode(';',$products[0]->preview); //ссылки на картинки передаем отдельным массивом
//     return view('layouts.index', ['products'=>$products, 'parameters'=>$parameters, 'images'=>$images, 'categories'=>$categories]);
// });

Route::get('/', 'ProductsController@indexFront');

Route::get('categories/products/show/{id}','FrontController@showProduct');


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::post('get_parameters','ParametersController@get');
Route::post('save_parameters','ParametersController@save');
Route::post('del_image','ProductsController@del_image');

Route::get('categories', 'FrontController@showCategories');
Route::get('categories/{id}', 'FrontController@showProductsOfCategory');
Route::get('contacts', 'FrontController@showContacts');
Route::get('documents', 'FrontController@showDocuments');

Route::get('/orders/{id}','OrdersController@create');
Route::post('/orders/{id}','OrdersController@store');
Route::match(['post','get'],'search','FrontController@search')->name('search');

app/Products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Products extends Model
{
    protected $fillable = ['title', 'descriptions', 'preview', 'meta_description', 'meta_keywords', 'category_id','public'];


	public static function parameters($id)
	{
	    return DB::table('products')->where('products.id','=',$id)
	        ->join('parameters_values', 'parameters_values.products_id', '=', 'products.id')
	        ->join('parameters', 'parameters_values.parameters_id', '=', 'parameters.id')
	        ->select('parameters.id','parameters.title', 'parameters_values.value', 'parameters.unit', 'products.preview')->get();
	}

	public static function del($id)
	{
		return DB::table('parameters_values')->where('products_id','=',$id)
		->join('parameters','parameters_values.parameters_id','=','parameters.id')
		->delete();
	}

	public function categories()
	{
		return $this->belongsToMany('App\Category', 'product_category', 'product_id', 'category_id');
	}

	public static function boot()
	{
		parent::boot();

		self::deleting(function($product)
		{
			$product->categories()->detach();
		});
	}

	public function order() 
	{
		return $this->belongsToMany('App\Order');
	}

	public function scopeSearchByKeyword($query, $keyword)
	{
		if ($keyword!='') {
			$query->where(function ($query) use ($keyword) {
				$query->where("title", "LIKE","%$keyword%")
				->orWhere("description", "LIKE", "%$keyword%")
				->orWhere("meta_description", "LIKE", "%$keyword%")
				->orWhere("meta_keywords", "LIKE", "%$keyword%");
			});
		}
		return $query;
	}	
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Products;
use App\Category;
use App\Parameters_values;
use App\Parameters;
use Validator;


class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        $this->authorize('index'); // <---- вот это важная строчка
        if($request->has('filter'))
        {
            $filter = $request->input('filter');
            $products = Products::whereHas('categories', function($q) use ($filter) {
                                    $q->whereIn('categories.id', $filter);
                                })->simplePaginate(10);
        } else {
            $filter = "";
            $products = Products::with('categories')->simplePaginate(10);
        }

        $categories = Category::all();
        $options = '';
        $options = ProductsController::recursiveArraySelect2($categories, $filter, $options);
        return view('admin.products.index', compact('categories', 'products', 'filter', 'options'));
    }

    public function indexFront()
    {
        $categories = Category::roots()->get();
        $tree = "";
        $categories = ProductsController::SidebarDropdowns($categories,$tree);
        $parameters = parameters::all();//получаем все параметры
        return view('layouts.index', ['parameters'=>$parameters, 'categories'=>$categories]);
    }

    static function ArrayDropdowns($array,$tree){
        foreach ($array as $value) {            
            if($value->isRoot()){
                $totalChild = $value->descendants()->count();
                $tree .= "<div class=\"btn-group dropdown\">\n";
                if($totalChild > 0){
                    $tree .= "<a id=\"dLabel\" role=\"button\" data-toggle=\"dropdown\" class=\"btn btn-default btn-drop\" data-target=\"#\" href=\"/categories/".$value->id."\">".$value->name." <span class=\"caret\"></span></a>\n";
                } else{
                    $tree .= "<a id=\"dLabel\" role=\"button\" data-toggle=\"dropdown\" class=\"btn btn-default  btn-drop\" data-target=\"#\" href=\"/categories/".$value->id."\">".$value->name."</a>\n";
                }
                if($totalChild > 0)
                {
                    $tree .= "<ul class=\"dropdown-menu multi-level\" role=\"menu\" aria-labelledby=\"dropdownMenu\">\n";
                    ProductsController::recursiveChildrensDropdowns($value->children()->get(),$tree);
                    $tree .= "</ul>\n";
                }
                $tree .= "</div>\n";
            }
        }
        return $tree;
    }

    static function recursiveChildrensDropdowns($children,&$tree){        
        foreach ($children as $value) { 
            if($value->descendants()->count() > 0){
                $tree .= "<li class=\"dropdown-submenu\">\n";
                $tree .= "<a tabindex=\"-1\" href=\"/categories/".$value->id."\">".$value->name."</a>\n";
                    $tree .= "<ul class=\"dropdown-menu\">\n";
                    ProductsController::recursiveChildrensDropdowns($value->children()->get(),$tree);
                    $tree .= "</ul>\n";
                $tree .= "</li>\n";
            } else{
                $tree .= "<li><a href=\"/categories/".$value->id."\">".$value->name."</a></li>\n";
            }
        }        
    }

    static function SidebarDropdowns($array,&$tree)
    {
      foreach ($array as $value) {
        $totalChild = count($value->children);
        if ($value->isRoot() and $totalChild == 0){
          $tree.= "<li>\n";
            $tree.= "<a href=\"/categories/".$value->id."\">".$value->name."</a>\n";
          $tree.= "</li>\n";
        } elseif ($value->isRoot() and $totalChild > 0){
          $tree.= "<li>\n";
            $tree.= "<a href=\"#\">".$value->name."<span class=\"fa arrow\"></span></a>\n";
                $tree.= "<ul class=\"nav nav-second-level\">\n"; 
                  ProductsController::SidebarDropdowns($value->children()->get(),$tree);
                $tree.= "</ul>\n";
          $tree.= "</li>\n";          
        }
        if($value->getLevel() > 0){
                $tree.= "<li>\n";
                  if(count($value->children) == 0){
                    $tree.= "<a href=\"/categories/".$value->id."\">".$value->name."</a>\n";
                  } else{
                    $tree.= "<a href=\"#\">".$value->name."<span class=\"fa arrow\"></span></a>\n";
                    if($value->getLevel() == 2){
                        $tree.= "<ul class=\"nav nav-third-level\">\n";
                    } else{
                        $tree.= "<ul class=\"nav nav-third-level\">\n";
                    }                    
                    ProductsController::SidebarDropdowns($value->children()->get(),$tree);
                    $tree.= "</ul>\n";
                  }                
                $tree.= "</li>\n";
        }
      }
      return $tree;
    } 

    function recursiveArraySelect2($array, $ids = null, $options)
    {
        foreach ($array as $value) {
            $totalChild = count($value->children);

            if(is_array($ids))
            {
                $ids = $ids;
            } else {
                $ids = array($ids);
            }

            if ($ids != null && in_array($value->id, $ids))
            {
                $options .= "<option value=\"$value->id\" selected>$value->name</option>";
            } else {
                $options .= "<option value=\"$value->id\">$value->name</option>";
            }

            ProductsController::recursiveArraySelect2($value->children, $ids, $options);
        }
        return $options;
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $this->authorize('create'); // <---- вот это важная строчка
        $categories = Category::getNestedList('name',null,'&nbsp;&nbsp;&nbsp;&nbsp;'); //выбираем все категории
        $parameters=Parameters::all();
        return view('admin.products.create', compact('categories','parameters'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function save(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|max:255',
            'description' => 'required',
            'category_id' => 'required',
            'meta_description' => 'required|max:255',
            'preview' => 'required',
            ]); 
        if(!$validator->fails())
        {
        $path = public_path()."/images/"; //определяем папку для сохранения картинок

                        //Сохраняем картинки
        $url_img=[];

        var_dump($request->file('preview'));
                     // массив, который будет содержать ссылки на все картинки
        if (is_array($request->file('preview'))){
            foreach($request->file('preview') as $file) //обрабатываем массив с файлами
            {

                if(empty($file)) continue;
                // если <input type="file"... есть, но туда ничего не загруженно, то пропускаем
                $extension = $file->getClientOriginalExtension();
                $filename = ProductsController::getRandomFileName($path, $extension);

                $url_img[]='/images/'.$filename.'.'.$extension; //добавляем url картинки в массив
                $file->move($path,$filename.'.'.$extension); //перемещаем файл в папку
            }
        }

        $preview=implode(';',$url_img); //массив с ссылками переводим в строку, что бы сохранить в базу.
        //Сохраняем каждый параметр
        $product=new Products;
        $product->title=$request->title; //название
        $product->description=$request->description;//описание
        $product->preview=$preview; //ссылки на картинки        
        $product->public=$request->public;
        $product->meta_description=$request->meta_description; // цена
        $product->meta_keywords=$request->meta_keywords; //ссылки на картинки
        $categories_id = $request->category_id;
        // $product->categories()->attach($categories_id);
        $product->save(); // Сохраняем все в базу.
        $product->categories()->sync($categories_id, false);
        //Обратабываем массивы с параметрами и их значениями.
        if (is_array($request->parameter)){
            $out=array_combine($request->parameter,$request->value);
        } // массив будет такой ['5'=>'300'], 5 - это id параметра, 300 - значение параметра
        //Сохраняем все параметры и значения в базу
        if(empty($out))
        {
            return back()->with('message','Товар сохранен');
        } //если нет ни одного параметра то просто редиректим обратно.

        foreach($out as $param=>$value)
        {
            $parameters=new Parameters_values;
            $parameters->parameters_id=$param;
            $parameters->products_id=$product->id;
            $parameters->value=$value;
            $parameters->save();
        }
        return back()->with('message','Товар сохранен');
    } else {
        $errorMsg = $validator->messages();
        return redirect()
        ->back()
        ->withErrors($errorMsg)
        ->withInput();
    }
}

    public static function getRandomFileName($path, $extension='')
    {
        $extension = $extension ? '.' . $extension : '';
        $path = $path ? $path . '/' : '';
 
        do {
            $name = md5(microtime() . rand(0, 9999));
            $file = $path . $name . $extension;
        } while (file_exists($file));
 
        return $name;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

resources/views/admin/products/create.blade.php
@extends('admin.main')
@section('content')
<!DOCTYPE html>
<html>
    <head>
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>Добавить товар</title>          
    </head>
    <body>
        @if(Session::has('message'))
        <div class="alert alert-success" role="alert">
          {{Session::get('message')}}
        </div>
        @endif
        @if (count($errors) > 0)
        <ul>
          @foreach ($errors->all() as $error)
          <div class="alert alert-warning" role="alert"><li>{{ $error }}</li></div>
          @endforeach
        </ul>
        @endif
        <div class="container">
        <form id="product-form" method="post" enctype="multipart/form-data">
            <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
            <ul class="breadcrumb">
              <li><a href="/adminzone/products">Назад</a> <span class="divider"></span></li>              
              <li class="active">Добавление товара</li>
            </ul>
            <h1>Добавить товар</h1>
            <hr>
            <div class="row">
                <div class="col-md-4{{ $errors->has('preview') ? ' has-error' : '' }}">
                    <input type="file" name="preview[]"/><br>
                    @if ($errors->has('preview'))
                    <span class="help-block">
                        <strong>{{ $errors->first('preview') }}</strong>
                    </span>
                    @endif
                </div>
                <div class="col-md-8">
                    <i class="glyphicon glyphicon-arrow-left"></i> Выберите миниатюру для товара. 
                    <p class="help-block">Размер изображения 150x150px, не более 200Кб</p>
                </div>
                </div>
            <div class="row">
                <div class="col-md-8">
                <h2>Дополнительные изображения</h2>
                <button class="btn btn-primary add_images" type="button"><i class="glyphicon glyphicon-plus"></i></button>
                <hr>
                </div>
            </div> 
            <div class="row">
                <div class="col-md-8"> 
                    <label for="category" class="control-label">Категория <span style="color:red">*</span></label><br>                    

<!--                     <div class="form-group">
                        <label for="parent" class="col-sm-2 control-label">Категория<span style="color:red">*</span></label>
                        <div class="col-sm-10{{ $errors->has('category_id') ? ' has-error' : '' }}"> -->
                            <div class="{{ $errors->has('category_id') ? ' has-error' : '' }}">
                            <select class="form-control multiselect" id="category_id" name="category_id[]" data-placeholder="Please select category" multiple="multiple">
                            @if(isset($category_id))
                                @foreach($category_id as $key => $category)
                                    <option value="{{$key}}" selected>{{$category}}</option>
                                @endforeach
                            @elseif(old('category_id')!=null)
                                @foreach($category_id=old('category_id') as $keyOld => $categoryOldId)
                                    @foreach($categories as $key => $categoryName)
                                        @if($key==$categoryOldId)        
                                            <option value="{{$key}}" selected>{{$categoryName}}</option>
                                        @endif
                                    @endforeach
                                @endforeach
                            @endif
                            @foreach($categories as $key => $category)
                            <option value="{{$key}}">{{$category}}</option>
                            @endforeach
                            </select>
<!--                         </div>
                    </div> -->
                    @if ($errors->has('category_id'))
                    <span class="help-block">
                        <strong>{{ $errors->first('category_id') }}</strong>
                    </span>
                    @endif
                    </div>
                    <label class="control-label" for="name">Название товара <span style="color:red">*</span></label>
                    <div class="{{ $errors->has('title') ? ' has-error' : '' }}">
                    <input class="form-control" type="text" name="title" value="@if(isset($product->title)){{ $product->title }}@else{{ old('title') }}@endif"/>
                    @if ($errors->has('title'))
                    <span class="help-block">
                        <strong>{{ $errors->first('title') }}</strong>
                    </span>
                    @endif
                    </div>
                    <label for="description" class="control-label">Описание товара <span style="color:red">*</span></label>
                    <textarea class="form-control" rows="4" name="description" id="editor">@if(isset($product->description)){{ $product->description }}@else{{ old('description') }}@endif</textarea>   
                    Опубликовать?<br>
                    @if ($errors->has('description'))
                    <span class="help-block">
                        <strong>{{ $errors->first('description') }}</strong>
                    </span>
                    @endif
                    <select name="public">
                        <option value="1">Да</option>
                        <option value="0">Нет</option>
                    </select>   
                    <h3>Мета</h3>                
                    <div class="row">
                        <div class="col-md-8">
                            <label for="meta_description" class="control-label">description <span style="color:red">*</span></label>
                            <div class="{{ $errors->has('meta_description') ? ' has-error' : '' }}">                   
                            <textarea class="form-control" type="text" name="meta_description" rows="3">@if(isset($product->meta_description)){{ $product->meta_description }}@else{{ old('meta_description') }}@endif</textarea>
                            @if ($errors->has('meta_description'))
                            <span class="help-block">
                                <strong>{{ $errors->first('meta_description') }}</strong>
                            </span>
                            @endif
                            </div>
                            keywords:<br>                            
                            <input class="form-control" type="text" name="meta_keywords" value="@if(isset($product->meta_keywords)){{ $product->meta_keywords }}@else{{ old('meta_keywords') }}@endif"/>                
                        </div>
                        <div class="col-md-4">
                        <i class="glyphicon glyphicon-arrow-left"></i> Заполните description кратким описанием товара. 
                        <p class="help-block">В поле keywords введите теги товара через запятую</p> 
                        </div>                        
                    </div>
                </div>
            </div>
            <h4>Характеристики товара</h4>
            <button class="btn btn-primary btn-lg add_button" type="button">Добавить</button><br><br>
            @if(!empty(old('parameter')))
            @foreach($parametersOld=old('parameter') as $keyParam => $parameterOld)
            <div class="form-inline borderes" role="form">
                <div class="form-group">
                    <label for="parameter" class="sr-only">Параметр</label>
                    <div class="input-group">
                        <span class="input-group-btn">
                        <button class="btn btn-default  add_parameter" type="button"><i class="glyphicon glyphicon-plus"></i></button>
                        </span>
                        <select class="form-control" name="parameter[]">
                            @foreach($parameters as $parameter)
                            @if($parameter->id==$parameterOld)
                            <option value="{{$parameterOld}}" selected>{{$parameter->title}} ({{$parameter->unit}})</option>
                            @else
                            <option value="{{$parameter->id}}">{{$parameter->title}} ({{$parameter->unit}})</option>
                            @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="value" class="sr-only">Значение параметра</label>
                        @if(!empty(old('value')))
                        @foreach($valuesOlds=old('value') as $keyVal => $valueOld)
                        @if($keyVal==$keyParam)
                        <input class="form-control" name="value[]" placeholder="Значение параметра" 
                        value="{{$valueOld}}"/>
                        @endif
                        @endforeach                        
                        @endif
                    </div>
                    <div class="form-group">
                        <span class="form-group-btn">
                        <button class="btn btn-default remove_button"><i class="glyphicon glyphicon-minus"></i></button>
                        </span>
                    </div>
                </div>
            </div>
            @endforeach
            @endif
            <br>
            <button class="btn btn-default btn-lg btn_save_item" type="submit">Сохранить товар</button>
            </form>
        </div>
    </body>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Добавить параметр</h4>
                </div>
                <div class="modal-body">
                    <input type="text" class="form-control parameter_modal" name="parameter" placeholder="Наименование параметра"/><br>
                    <input type="text" class="form-control unit_modal" name="unit" placeholder="Единица измерения"/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary save_and_close">Сохранить изменения</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function() {
            $(".multiselect").select2();
        });
    </script>
</html>
@endsection

resources/views/admin/products/index.blade.php
@extends('admin.main')
@section('content')
<ul class="breadcrumb">          
  <li class="active">Все товары</li>
</ul>

<div class="panel panel-default">
    <div class="panel-heading">Продукты&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{{ route('products.create') }}" class="btn btn-xs btn-success">&nbsp;&nbsp;Создать&nbsp;&nbsp;</a>
    </div>
    <div class="panel-body">
        <div class="col-xs-offset-8 col-xs-4" style="margin-bottom: 15px;">
            <form id="filter" action="{{route('products.index')}}" method="get">{!! csrf_field() !!}<select name="filter[]" data-placeholder="Фильтр категорий" class="form-control multiselect" multiple="multiple">
                {!! $options !!}
            </select></form>
        </div>
        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th class="col-md-2">Изображение</th>
                    <th class="col-md-3">Название</th>                    
                    <th class="col-md-2">Категория(ии)</th>
                    <th class="col-md-2 text-center">Действия</th>
                </tr>
            </thead>
            <tbody>
                @foreach($products as $product)
                <tr>
                    <?php 
                    $images=explode(';',$product->preview);
                    ?>
                    <td>
                        <img src="{{$images[0]}}" width="130" class="img-responsive img-rounded" alt="{{ $product->title }}">
                    </td>
                    <td>{{ $product->title}}</td>                    
                    <td>
                        @foreach($product->categories as $index => $category)
                        {{ $category->name }}@if($index+1 < count($product->categories)),@endif
                        @endforeach
                    </td>
                    <td class="text-center">
                        <form class="form-inline">
                            <a href="{{ route('products.edit', ['products' => $product->id]) }}" class="btn btn-xs btn-warning" data-toggle="tooltip" data-placement="top" title="Изменить">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </a>
                            <a href="{{ route('products.destroy', ['products' => $product->id]) }}" class="btn btn-xs btn-danger" data-toggle="tooltip" data-placement="top" data-delete="{{ csrf_token() }}" title="Удалить">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </a>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{ $products->links() }}
    </div>
</div>
<script type="text/javascript">
    $(function() {
        $('[data-toggle="tooltip"]').tooltip();

        $(".multiselect").select2();

        $('.multiselect').on("change", function() {
            var categories = $('.multiselect').val();
            console.log(categories);

            $("#filter").submit();
        });

        $('[data-delete]').click(function(e){
            e.preventDefault();
                // If the user confirm the delete
                if (confirm('Do you really want to delete this product?')) {
                    // Get the route URL
                    var url = $(this).prop('href');
                    // Get the token
                    var token = $(this).data('delete');
                    // Create a form element
                    var $form = $('<form/>', {action: url, method: 'post'});
                    // Add the DELETE hidden input method
                    var $inputMethod = $('<input/>', {type: 'hidden', name: '_method', value: 'delete'});
                    // Add the token hidden input
                    var $inputToken = $('<input/>', {type: 'hidden', name: '_token', value: token});
                    // Append the inputs to the form, hide the form, append the form to the <body>, SUBMIT !
                    $form.append($inputMethod, $inputToken).hide().appendTo('body').submit();
                }
            }       );
    });
</script>

@if(Session::has('message'))
{{Session::get('message')}}
@endif
@endsection